server {
    listen 80;
    # Public IP provided by user
    server_name {{SERVER_NAME}};

    location / {
        include proxy_params;
        # Proxy pass to the socket defined in gunicorn config
        proxy_pass http://unix:{{APP_DIR}}/mi_app.sock;
    }

    location /static {
        alias {{APP_DIR}}/static;
        expires 30d;
    }
}
